spring:
    jpa:
        show-sql: true
#        properties:
#            hibernate.format_sql: true
    datasource:
        url: jdbc:mysql://192.168.194.76:3306/solomon_info
        username: root
        password: 123456

    rabbitmq:
        host: 121.42.192.175
        port: 5672
        username: guest
        password: guest

