spring:
    jpa:
        show-sql: true
#        properties:
#            hibernate.format_sql: true
    datasource:
#        url: jdbc:mysql://192.168.194.76:3306/solomon_info
        url: jdbc:mysql://localhost:3306/zixun_spider
        username: root
        password: root

    rabbitmq:
        host: 121.42.192.175
        port: 5672
        username: guest
        password: guest

    data:
        mongodb:
            host: 121.42.192.175
            port: 27017
            database: spider_article

server:
    port: 8000


